import { Inter } from "next/font/google";
import "../../css/0aac42dd03f7be51.css"
import "../../css/06556c4f804673da.css"
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Header/>

        {children}
      </body>
    </html>
  );
}
